import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      ".open-next/**",
      "cloudflare-env.d.ts", // ← auto-generated by wrangler, don't lint
      "scripts/**", // ← Node scripts, not app code
    ],
  },
  {
    languageOptions: {
      globals: {
        // Node.js globals for scripts
        process: "readonly",
        console: "readonly",
      },
    },
    rules: {
      "@typescript-eslint/no-unused-vars": "warn",
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-require-imports": "warn",
    },
  },
);
